#pragma once

#include "NativeGameplayTags.h"

namespace XGRPGGameplayTags
{

	XGRPG_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);

	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Melee);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AirAttack);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_1);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_2);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_3);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_4);


	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);


	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	XGRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

};