#pragma once

#include "NativeGameplayTags.h"

namespace LSRPGGameplayTags
{

	LSRPG_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);

	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Melee);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AirAttack);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_1);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_2);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_3);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_4);


	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);


	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	LSRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

};